
addressesGit = {
    "bielsko-biala":   "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/bielsko-biala.json",
    "bydgoszcz":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/bydgoszcz.json",
    "bytom":           "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/bytom.json",
    "cieszyn":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/cieszyn.json",
    "jurajska":        "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/jurajska.json",
    "wolnosc":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/wolnosc.json",
    "elblag":          "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/elblag.json",
    "gliwice":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/gliwice.json",
    "punkt44":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/punkt44.json",
    "silesia":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/silesia.json",
    "bonarka":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/bonarka.json",
    "kazimierz":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/kazimierz.json",
    "zakopianka":      "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/zakopianka.json",
    "felicity":        "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/felicity.json",
    "lublinplaza":     "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/lublinplaza.json",
    "manufaktura":     "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/manufaktura.json",
    "kinepolis":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/kinepolis.json",
    "poznanplaza":     "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/poznanplaza.json",
    "rudaslaska":      "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/rudaslaska.json",
    "rybnik":          "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/rybnik.json",
    "sosnowiec":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/sosnowiec.json",
    "starogard":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/starogard.json",
    "czerwonadroga":   "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/czerwonadroga.json",
    "torunplaza":      "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/torunplaza.json",
    "walbrzych":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/walbrzych.json",
    "arkadia":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/arkadia.json",
    "bemowo":          "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/bemowo.json",
    "galeriapolnocna": "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/galeriapolnocna.json",
    "mokotow":         "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/mokotow.json",
    "janki":           "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/janki.json",
    "promenada":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/promenada.json",
    "sadyba":          "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/sadyba.json",
    "korona":          "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/korona.json",
    "wroclavia":       "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/wroclavia.json",
    "zielonagora":     "https://raw.githubusercontent.com/145211/Cinema-City-Planner/master/screenings/zielonagora.json"
}
